/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package supertetris.tests;

import java.awt.event.KeyEvent;
import static java.awt.event.KeyEvent.*;
import java.io.File;
import java.util.logging.Level;
import java.util.logging.Logger;
import supertetris.boards.ConfigGame;

/**
 *
 * @author Andre
 */
public class TestControlMenu extends javax.swing.JFrame {

    ConfigGame config;

    int keyLeft = VK_LEFT;
    int keyRight = VK_RIGHT;
    int keyDown = VK_DOWN;
    int keyRotate = VK_SPACE;
    int keyFall = VK_ENTER;

    /**
     * Creates new form TestControlMeno
     */
    public TestControlMenu() {
        initComponents();
        chLeftBt.setText(KeyEvent.getKeyText(keyLeft));
        chRightBt.setText(KeyEvent.getKeyText(keyRight));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialogChLeft = new javax.swing.JDialog();
        txtLeft = new javax.swing.JTextField();
        exitChLeft = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        dialogChRight = new javax.swing.JDialog();
        txtRight = new javax.swing.JTextField();
        exitChLeft1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        chLeftBt = new javax.swing.JButton();
        btDftCfg = new javax.swing.JButton();
        btCancel = new javax.swing.JButton();
        btSaveCfg = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        chRightBt = new javax.swing.JButton();

        dialogChLeft.setMaximumSize(new java.awt.Dimension(400, 300));
        dialogChLeft.setMinimumSize(new java.awt.Dimension(400, 300));

        txtLeft.setEditable(false);
        txtLeft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLeftActionPerformed(evt);
            }
        });
        txtLeft.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtLeftKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtLeftKeyTyped(evt);
            }
        });

        exitChLeft.setText("jButton1");
        exitChLeft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitChLeftActionPerformed(evt);
            }
        });

        jLabel1.setText("Chose a Key to move Left:");

        javax.swing.GroupLayout dialogChLeftLayout = new javax.swing.GroupLayout(dialogChLeft.getContentPane());
        dialogChLeft.getContentPane().setLayout(dialogChLeftLayout);
        dialogChLeftLayout.setHorizontalGroup(
            dialogChLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogChLeftLayout.createSequentialGroup()
                .addGroup(dialogChLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dialogChLeftLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtLeft, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(dialogChLeftLayout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(exitChLeft)))
                .addContainerGap(108, Short.MAX_VALUE))
        );
        dialogChLeftLayout.setVerticalGroup(
            dialogChLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogChLeftLayout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addGroup(dialogChLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLeft, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                .addComponent(exitChLeft)
                .addGap(27, 27, 27))
        );

        dialogChRight.setMaximumSize(new java.awt.Dimension(400, 300));
        dialogChRight.setMinimumSize(new java.awt.Dimension(400, 300));

        txtRight.setEditable(false);
        txtRight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRightActionPerformed(evt);
            }
        });
        txtRight.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtRightKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRightKeyTyped(evt);
            }
        });

        exitChLeft1.setText("jButton1");
        exitChLeft1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitChLeft1ActionPerformed(evt);
            }
        });

        jLabel4.setText("Chose a Key to move Right:");

        javax.swing.GroupLayout dialogChRightLayout = new javax.swing.GroupLayout(dialogChRight.getContentPane());
        dialogChRight.getContentPane().setLayout(dialogChRightLayout);
        dialogChRightLayout.setHorizontalGroup(
            dialogChRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogChRightLayout.createSequentialGroup()
                .addGroup(dialogChRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dialogChRightLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(txtRight, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(dialogChRightLayout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(exitChLeft1)))
                .addContainerGap(100, Short.MAX_VALUE))
        );
        dialogChRightLayout.setVerticalGroup(
            dialogChRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogChRightLayout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addGroup(dialogChRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRight, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                .addComponent(exitChLeft1)
                .addGap(27, 27, 27))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        chLeftBt.setText("Change Left Key");
        chLeftBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chLeftBtActionPerformed(evt);
            }
        });

        btDftCfg.setText("Restore Defaults");
        btDftCfg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDftCfgActionPerformed(evt);
            }
        });

        btCancel.setText("Cancel");
        btCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelActionPerformed(evt);
            }
        });

        btSaveCfg.setText("Done");
        btSaveCfg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSaveCfgActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("LEFT");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("RIGHT");

        chRightBt.setText("Change Right Key");
        chRightBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chRightBtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chLeftBt, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chRightBt, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btDftCfg)
                        .addGap(18, 18, 18)
                        .addComponent(btSaveCfg, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(147, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(chLeftBt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(chRightBt, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(218, 218, 218)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btDftCfg)
                    .addComponent(btCancel)
                    .addComponent(btSaveCfg))
                .addContainerGap(191, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtLeftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLeftActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLeftActionPerformed

    private void txtLeftKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLeftKeyTyped

    }//GEN-LAST:event_txtLeftKeyTyped

    private void exitChLeftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitChLeftActionPerformed
        dialogChLeft.hide();
    }//GEN-LAST:event_exitChLeftActionPerformed

    private void chLeftBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chLeftBtActionPerformed
        dialogChLeft.setVisible(true);
    }//GEN-LAST:event_chLeftBtActionPerformed

    private void txtLeftKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLeftKeyPressed
        int keyCode = evt.getKeyCode(); // Using KeyEvent.VK_SPACE for Space key
        keyLeft = keyCode;
        String keyName = KeyEvent.getKeyText(keyCode);
        txtLeft.setText(keyName);
        chLeftBt.setText(keyName);        // TODO add your handling code here:
    }//GEN-LAST:event_txtLeftKeyPressed

    private void btCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelActionPerformed
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btCancelActionPerformed

    private void txtRightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRightActionPerformed

    private void txtRightKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRightKeyPressed
        int keyCode = evt.getKeyCode(); // Using KeyEvent.VK_SPACE for Space key
        keyRight = keyCode;
        String keyName = KeyEvent.getKeyText(keyCode);
        txtRight.setText(keyName);
        chRightBt.setText(keyName);
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRightKeyPressed

    private void txtRightKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRightKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRightKeyTyped

    private void exitChLeft1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitChLeft1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_exitChLeft1ActionPerformed

    private void chRightBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chRightBtActionPerformed
        dialogChRight.setVisible(true);
    }//GEN-LAST:event_chRightBtActionPerformed

    private void btSaveCfgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSaveCfgActionPerformed
        File cfg = new File("config.cfg");
        cfg.delete();
        config = new ConfigGame(keyLeft, keyRight, keyDown, keyRotate, keyFall);
        try {
            config.saveConfig();
        } catch (Exception ex) {
            System.out.println("UNKOWN ERROR");
        }
        this.dispose();
    }//GEN-LAST:event_btSaveCfgActionPerformed

    private void btDftCfgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDftCfgActionPerformed
        keyLeft = VK_LEFT; chLeftBt.setText(KeyEvent.getKeyText(keyLeft));
        keyRight = VK_RIGHT; chRightBt.setText(KeyEvent.getKeyText(keyRight));
        keyDown = VK_DOWN; 
        keyRotate = VK_SPACE;
        keyFall = VK_ENTER;
        
        
    }//GEN-LAST:event_btDftCfgActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TestControlMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TestControlMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TestControlMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TestControlMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TestControlMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCancel;
    private javax.swing.JButton btDftCfg;
    private javax.swing.JButton btSaveCfg;
    private javax.swing.JButton chLeftBt;
    private javax.swing.JButton chRightBt;
    private javax.swing.JDialog dialogChLeft;
    private javax.swing.JDialog dialogChRight;
    private javax.swing.JButton exitChLeft;
    private javax.swing.JButton exitChLeft1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtLeft;
    private javax.swing.JTextField txtRight;
    // End of variables declaration//GEN-END:variables
}
