package supertetris.ui;

/**
 * this UI is used for the about menu in the tetris game
 * @author Andre Benquerer - n° 24633 
 */
public class AboutUs extends javax.swing.JFrame {

    /**
     * Creates new form AboutUs
     */
    public AboutUs() {
        initComponents();
        //sets the frame to the middle of the screen
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AndreInfo = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        pnlImage = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pnlInfo = new javax.swing.JPanel();
        jTextArea1 = new javax.swing.JTextArea();
        AboutProj = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jTextPane1 = new javax.swing.JTextPane();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pnlMain = new javax.swing.JPanel();
        pnlRight = new javax.swing.JPanel();
        pnlUp = new javax.swing.JPanel();
        pnlLeft = new javax.swing.JPanel();
        pnlBottom = new javax.swing.JPanel();
        jButton8 = new javax.swing.JButton();
        pnlButtons = new javax.swing.JPanel();
        btAndre = new javax.swing.JButton();
        btProj = new javax.swing.JButton();

        AndreInfo.setAlwaysOnTop(true);
        AndreInfo.setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 0, 51));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jSeparator1.setPreferredSize(new java.awt.Dimension(3, 3));
        jPanel1.add(jSeparator1, java.awt.BorderLayout.CENTER);

        pnlImage.setPreferredSize(new java.awt.Dimension(295, 365));
        pnlImage.setLayout(new javax.swing.BoxLayout(pnlImage, javax.swing.BoxLayout.PAGE_AXIS));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/supertetris/resources/My project.jpg"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(330, 400));
        pnlImage.add(jLabel1);

        jPanel1.add(pnlImage, java.awt.BorderLayout.LINE_START);

        pnlInfo.setMinimumSize(new java.awt.Dimension(400, 100));
        pnlInfo.setPreferredSize(new java.awt.Dimension(250, 250));
        pnlInfo.setLayout(new javax.swing.BoxLayout(pnlInfo, javax.swing.BoxLayout.LINE_AXIS));

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(0, 0, 51));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(10);
        jTextArea1.setText("Nome: André Ribeiro Benquerer\nNúmero: 24633\nEmail: aluno24633@ipt.pt\nCurso: Engenharia Informática\nAno: 1°     | Turma: A\n\n\"Sou brasileiro... Cheguei em Portugal no meio de setembro de 2022. Minha primeira vez na Europa, e pela primeira vez indo morar em uma cidade diferente de onde nasci, vim direto para Tomar começar o curso.\nO que me motivou a escolher engenharia informática foi a ideia de trabalhar em desenvolvimento de jogos, mas ao ter contato com outras áreas da informática, posso dizer que ainda não decidi meu futuro... Vamos ver no final do curso\" ");
        jTextArea1.setWrapStyleWord(true);
        jTextArea1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlInfo.add(jTextArea1);

        jPanel1.add(pnlInfo, java.awt.BorderLayout.EAST);

        javax.swing.GroupLayout AndreInfoLayout = new javax.swing.GroupLayout(AndreInfo.getContentPane());
        AndreInfo.getContentPane().setLayout(AndreInfoLayout);
        AndreInfoLayout.setHorizontalGroup(
            AndreInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AndreInfoLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        AndreInfoLayout.setVerticalGroup(
            AndreInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        AboutProj.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        AboutProj.setAlwaysOnTop(true);
        AboutProj.setBackground(new java.awt.Color(0, 0, 51));
        AboutProj.setResizable(false);
        AboutProj.getContentPane().setLayout(new java.awt.BorderLayout(0, 10));

        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.Y_AXIS));

        jPanel3.setPreferredSize(new java.awt.Dimension(330, 300));
        jPanel3.setLayout(new java.awt.BorderLayout());

        jTextPane1.setEditable(false);
        jTextPane1.setBackground(new java.awt.Color(0, 0, 51));
        jTextPane1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextPane1.setForeground(new java.awt.Color(255, 255, 255));
        jTextPane1.setText("Our project aims to develop a Tetris game using Java programming language. Tetris is a classic puzzle game where players arrange falling blocks called tetrominoes to create complete horizontal lines. With our implementation, we aim to provide an enjoyable gaming experience while showcasing our Java programming skills. By developing this Tetris game project in Java, we aim to showcase our skills in game development and object-oriented programming. We are excited to create an engaging and challenging gaming experience for players while demonstrating our understanding of Java programming concepts and libraries");
        jTextPane1.setPreferredSize(new java.awt.Dimension(300, 20));
        jPanel3.add(jTextPane1, java.awt.BorderLayout.CENTER);

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText(" About the Project");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel3.add(jLabel4, java.awt.BorderLayout.PAGE_START);

        jPanel4.add(jPanel3);

        AboutProj.getContentPane().add(jPanel4, java.awt.BorderLayout.CENTER);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Informations");
        getContentPane().add(jLabel2, java.awt.BorderLayout.NORTH);

        pnlMain.setBackground(new java.awt.Color(0, 0, 51));
        pnlMain.setLayout(new java.awt.BorderLayout());

        pnlRight.setBackground(new java.awt.Color(0, 0, 51));
        pnlRight.setPreferredSize(new java.awt.Dimension(100, 200));

        javax.swing.GroupLayout pnlRightLayout = new javax.swing.GroupLayout(pnlRight);
        pnlRight.setLayout(pnlRightLayout);
        pnlRightLayout.setHorizontalGroup(
            pnlRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        pnlRightLayout.setVerticalGroup(
            pnlRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        pnlMain.add(pnlRight, java.awt.BorderLayout.LINE_END);

        pnlUp.setBackground(new java.awt.Color(0, 0, 51));
        pnlUp.setPreferredSize(new java.awt.Dimension(20, 50));

        javax.swing.GroupLayout pnlUpLayout = new javax.swing.GroupLayout(pnlUp);
        pnlUp.setLayout(pnlUpLayout);
        pnlUpLayout.setHorizontalGroup(
            pnlUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlUpLayout.setVerticalGroup(
            pnlUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        pnlMain.add(pnlUp, java.awt.BorderLayout.NORTH);

        pnlLeft.setBackground(new java.awt.Color(0, 0, 51));
        pnlLeft.setPreferredSize(new java.awt.Dimension(100, 200));

        javax.swing.GroupLayout pnlLeftLayout = new javax.swing.GroupLayout(pnlLeft);
        pnlLeft.setLayout(pnlLeftLayout);
        pnlLeftLayout.setHorizontalGroup(
            pnlLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        pnlLeftLayout.setVerticalGroup(
            pnlLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        pnlMain.add(pnlLeft, java.awt.BorderLayout.WEST);

        pnlBottom.setBackground(new java.awt.Color(0, 0, 51));
        pnlBottom.setPreferredSize(new java.awt.Dimension(20, 50));
        pnlBottom.setLayout(new java.awt.BorderLayout(20, 10));

        jButton8.setBackground(new java.awt.Color(0, 0, 0));
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("Close");
        jButton8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        pnlBottom.add(jButton8, java.awt.BorderLayout.EAST);

        pnlMain.add(pnlBottom, java.awt.BorderLayout.SOUTH);

        pnlButtons.setBackground(new java.awt.Color(0, 0, 51));
        pnlButtons.setPreferredSize(new java.awt.Dimension(250, 500));
        pnlButtons.setRequestFocusEnabled(false);
        pnlButtons.setLayout(new java.awt.GridLayout(3, 0, 0, 60));

        btAndre.setBackground(new java.awt.Color(0, 0, 0));
        btAndre.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btAndre.setForeground(new java.awt.Color(255, 255, 255));
        btAndre.setText("André Benquerer");
        btAndre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 4));
        btAndre.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btAndre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAndreActionPerformed(evt);
            }
        });
        pnlButtons.add(btAndre);

        btProj.setBackground(new java.awt.Color(0, 0, 0));
        btProj.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btProj.setForeground(new java.awt.Color(255, 255, 255));
        btProj.setText("About the Project");
        btProj.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 4));
        btProj.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btProj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btProjActionPerformed(evt);
            }
        });
        pnlButtons.add(btProj);

        pnlMain.add(pnlButtons, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnlMain, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void btAndreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAndreActionPerformed
        //sets the size of the dialog
        AndreInfo.setSize(560, 430);
        //sets the dialog to the middle of the screen
        AndreInfo.setLocationRelativeTo(null);
        //makes the dialog visible
        AndreInfo.setVisible(true);
    }//GEN-LAST:event_btAndreActionPerformed

    private void btProjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btProjActionPerformed
        //sets the size of the dialog
        AboutProj.setSize(480, 330);
        //sets the dialog to the middle of the screen
        AboutProj.setLocationRelativeTo(null);
        //makes the dialog visible
        AboutProj.setVisible(true);
    }//GEN-LAST:event_btProjActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AboutUs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AboutUs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AboutUs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AboutUs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AboutUs().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog AboutProj;
    private javax.swing.JDialog AndreInfo;
    private javax.swing.JButton btAndre;
    private javax.swing.JButton btProj;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JPanel pnlBottom;
    private javax.swing.JPanel pnlButtons;
    private javax.swing.JPanel pnlImage;
    private javax.swing.JPanel pnlInfo;
    private javax.swing.JPanel pnlLeft;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JPanel pnlRight;
    private javax.swing.JPanel pnlUp;
    // End of variables declaration//GEN-END:variables
}
