package supertetris.ui;

import java.awt.event.KeyEvent;
import static java.awt.event.KeyEvent.*;
import java.io.File;
import java.util.logging.Level;
import java.util.logging.Logger;
import supertetris.boards.ConfigGame;

/**
 * this UI is used for the controls menu in the tetris game
 * @author Andre Benquerer - n° 24633
 */
public class ControlsMenu extends javax.swing.JFrame {
    
    //Initiate Config
    ConfigGame config;
    
    //Variables for binds  
    int keyLeft = VK_LEFT; //initiates keyLeft with "left arrow" key code
    int keyRight = VK_RIGHT; //initiates keyRight with "right arrow" key code
    int keyDown = VK_DOWN; //initiates keyDown with "down arrow" key code
    int keyRotate = VK_SPACE; //initiates keyRotate with "space" key code
    int keyFall = VK_ENTER; //initiates keyFall with left "enter" key code
    

    /**
     * Creates new form ControlsMenu
     */
    public ControlsMenu() {
        initComponents();
        setLocationRelativeTo(null);
        try {
            //get current key based on config 
            ConfigGame cfg = ConfigGame.loadConfig();
            btChLeft.setText(KeyEvent.getKeyText(cfg.getLeftkey())); 
            btChRight.setText(KeyEvent.getKeyText(cfg.getRigtkey())); 
            btChDown.setText(KeyEvent.getKeyText(cfg.getDownkey())); 
            btChRotate.setText(KeyEvent.getKeyText(cfg.getRotatekey())); 
            btChFall.setText(KeyEvent.getKeyText(cfg.getFalldownkey()));      
        } catch (Exception ex) {
            //no config means still got to choose
            btChLeft.setText("CLICK TO CHOOSE"); //current key?
            btChRight.setText("CLICK TO CHOOSE"); //current key?
            btChDown.setText("CLICK TO CHOOSE"); //current key?
            btChRotate.setText("CLICK TO CHOOSE"); //current key?
            btChFall.setText("CLICK TO CHOOSE"); //current key?  
        }
                    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialogChLeft = new javax.swing.JDialog();
        chLeftPanel = new javax.swing.JPanel();
        txtChLeft = new javax.swing.JTextField();
        btExitLeft = new javax.swing.JButton();
        lbChLeft = new javax.swing.JLabel();
        dialogChRight = new javax.swing.JDialog();
        chRightPanel = new javax.swing.JPanel();
        txtChRight = new javax.swing.JTextField();
        btExitRight = new javax.swing.JButton();
        lbChRight = new javax.swing.JLabel();
        dialogChDown = new javax.swing.JDialog();
        chDownPanel = new javax.swing.JPanel();
        txtChDown = new javax.swing.JTextField();
        btExitDown = new javax.swing.JButton();
        lbChDown = new javax.swing.JLabel();
        dialogChRotate = new javax.swing.JDialog();
        chRotatePanel = new javax.swing.JPanel();
        txtChRotate = new javax.swing.JTextField();
        btExitRotate = new javax.swing.JButton();
        lbChRotate = new javax.swing.JLabel();
        dialogChFall = new javax.swing.JDialog();
        chFallPanel = new javax.swing.JPanel();
        txtChFall = new javax.swing.JTextField();
        btExitFall = new javax.swing.JButton();
        lbChFall = new javax.swing.JLabel();
        configName = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtNameCfg = new javax.swing.JTextField();
        btNameCfgFinish = new javax.swing.JButton();
        mainPanel = new javax.swing.JPanel();
        lbDown = new javax.swing.JLabel();
        lbLeft = new javax.swing.JLabel();
        lbRight = new javax.swing.JLabel();
        lbRotate = new javax.swing.JLabel();
        lbFall = new javax.swing.JLabel();
        btChDown = new javax.swing.JButton();
        btChLeft = new javax.swing.JButton();
        btChFall = new javax.swing.JButton();
        btChRight = new javax.swing.JButton();
        btChRotate = new javax.swing.JButton();
        btResDft = new javax.swing.JButton();
        btSave = new javax.swing.JButton();
        btCancel = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btDone = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        lbnameCfg = new javax.swing.JLabel();

        dialogChLeft.setMinimumSize(new java.awt.Dimension(300, 300));
        dialogChLeft.setResizable(false);

        chLeftPanel.setBackground(new java.awt.Color(0, 0, 51));
        chLeftPanel.setForeground(new java.awt.Color(255, 255, 255));
        chLeftPanel.setMaximumSize(new java.awt.Dimension(300, 300));
        chLeftPanel.setMinimumSize(new java.awt.Dimension(300, 300));
        chLeftPanel.setPreferredSize(new java.awt.Dimension(300, 300));

        txtChLeft.setEditable(false);
        txtChLeft.setBackground(new java.awt.Color(102, 102, 102));
        txtChLeft.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtChLeft.setForeground(new java.awt.Color(255, 255, 255));
        txtChLeft.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtChLeft.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtChLeftKeyPressed(evt);
            }
        });

        btExitLeft.setBackground(new java.awt.Color(0, 0, 0));
        btExitLeft.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btExitLeft.setForeground(new java.awt.Color(255, 255, 255));
        btExitLeft.setText("DONE");
        btExitLeft.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btExitLeft.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btExitLeft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExitLeftActionPerformed(evt);
            }
        });

        lbChLeft.setForeground(new java.awt.Color(255, 255, 255));
        lbChLeft.setText("PRESS A KEY TO SELECT");

        javax.swing.GroupLayout chLeftPanelLayout = new javax.swing.GroupLayout(chLeftPanel);
        chLeftPanel.setLayout(chLeftPanelLayout);
        chLeftPanelLayout.setHorizontalGroup(
            chLeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, chLeftPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lbChLeft, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtChLeft, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
            .addGroup(chLeftPanelLayout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(btExitLeft, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        chLeftPanelLayout.setVerticalGroup(
            chLeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(chLeftPanelLayout.createSequentialGroup()
                .addContainerGap(91, Short.MAX_VALUE)
                .addGroup(chLeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtChLeft, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                    .addComponent(lbChLeft, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(58, 58, 58)
                .addComponent(btExitLeft)
                .addGap(83, 83, 83))
        );

        javax.swing.GroupLayout dialogChLeftLayout = new javax.swing.GroupLayout(dialogChLeft.getContentPane());
        dialogChLeft.getContentPane().setLayout(dialogChLeftLayout);
        dialogChLeftLayout.setHorizontalGroup(
            dialogChLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(dialogChLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(dialogChLeftLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(chLeftPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        dialogChLeftLayout.setVerticalGroup(
            dialogChLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(dialogChLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(dialogChLeftLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(chLeftPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        dialogChRight.setMinimumSize(new java.awt.Dimension(300, 300));
        dialogChRight.setResizable(false);

        chRightPanel.setBackground(new java.awt.Color(0, 0, 51));
        chRightPanel.setForeground(new java.awt.Color(255, 255, 255));
        chRightPanel.setMaximumSize(new java.awt.Dimension(300, 300));
        chRightPanel.setMinimumSize(new java.awt.Dimension(300, 300));

        txtChRight.setEditable(false);
        txtChRight.setBackground(new java.awt.Color(102, 102, 102));
        txtChRight.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtChRight.setForeground(new java.awt.Color(255, 255, 255));
        txtChRight.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtChRight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtChRightActionPerformed(evt);
            }
        });
        txtChRight.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtChRightKeyPressed(evt);
            }
        });

        btExitRight.setBackground(new java.awt.Color(0, 0, 0));
        btExitRight.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btExitRight.setForeground(new java.awt.Color(255, 255, 255));
        btExitRight.setText("DONE");
        btExitRight.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btExitRight.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btExitRight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExitRightActionPerformed(evt);
            }
        });

        lbChRight.setForeground(new java.awt.Color(255, 255, 255));
        lbChRight.setText("PRESS A KEY TO SELECT");

        javax.swing.GroupLayout chRightPanelLayout = new javax.swing.GroupLayout(chRightPanel);
        chRightPanel.setLayout(chRightPanelLayout);
        chRightPanelLayout.setHorizontalGroup(
            chRightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, chRightPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lbChRight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtChRight, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
            .addGroup(chRightPanelLayout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(btExitRight, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        chRightPanelLayout.setVerticalGroup(
            chRightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(chRightPanelLayout.createSequentialGroup()
                .addContainerGap(91, Short.MAX_VALUE)
                .addGroup(chRightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtChRight, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                    .addComponent(lbChRight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(58, 58, 58)
                .addComponent(btExitRight)
                .addGap(83, 83, 83))
        );

        javax.swing.GroupLayout dialogChRightLayout = new javax.swing.GroupLayout(dialogChRight.getContentPane());
        dialogChRight.getContentPane().setLayout(dialogChRightLayout);
        dialogChRightLayout.setHorizontalGroup(
            dialogChRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(dialogChRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(dialogChRightLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(chRightPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        dialogChRightLayout.setVerticalGroup(
            dialogChRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(dialogChRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(dialogChRightLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(chRightPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        dialogChDown.setMinimumSize(new java.awt.Dimension(300, 300));
        dialogChDown.setResizable(false);

        chDownPanel.setBackground(new java.awt.Color(0, 0, 51));
        chDownPanel.setForeground(new java.awt.Color(255, 255, 255));
        chDownPanel.setMaximumSize(new java.awt.Dimension(300, 300));
        chDownPanel.setMinimumSize(new java.awt.Dimension(300, 300));

        txtChDown.setEditable(false);
        txtChDown.setBackground(new java.awt.Color(102, 102, 102));
        txtChDown.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtChDown.setForeground(new java.awt.Color(255, 255, 255));
        txtChDown.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtChDown.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtChDownKeyPressed(evt);
            }
        });

        btExitDown.setBackground(new java.awt.Color(0, 0, 0));
        btExitDown.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btExitDown.setForeground(new java.awt.Color(255, 255, 255));
        btExitDown.setText("DONE");
        btExitDown.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btExitDown.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btExitDown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExitDownActionPerformed(evt);
            }
        });

        lbChDown.setForeground(new java.awt.Color(255, 255, 255));
        lbChDown.setText("PRESS A KEY TO SELECT");

        javax.swing.GroupLayout chDownPanelLayout = new javax.swing.GroupLayout(chDownPanel);
        chDownPanel.setLayout(chDownPanelLayout);
        chDownPanelLayout.setHorizontalGroup(
            chDownPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, chDownPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lbChDown, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtChDown, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
            .addGroup(chDownPanelLayout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(btExitDown, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        chDownPanelLayout.setVerticalGroup(
            chDownPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(chDownPanelLayout.createSequentialGroup()
                .addContainerGap(91, Short.MAX_VALUE)
                .addGroup(chDownPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtChDown, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                    .addComponent(lbChDown, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(58, 58, 58)
                .addComponent(btExitDown)
                .addGap(83, 83, 83))
        );

        javax.swing.GroupLayout dialogChDownLayout = new javax.swing.GroupLayout(dialogChDown.getContentPane());
        dialogChDown.getContentPane().setLayout(dialogChDownLayout);
        dialogChDownLayout.setHorizontalGroup(
            dialogChDownLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(dialogChDownLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(dialogChDownLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(chDownPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        dialogChDownLayout.setVerticalGroup(
            dialogChDownLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(dialogChDownLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(dialogChDownLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(chDownPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        dialogChRotate.setMinimumSize(new java.awt.Dimension(300, 300));
        dialogChRotate.setResizable(false);

        chRotatePanel.setBackground(new java.awt.Color(0, 0, 51));
        chRotatePanel.setForeground(new java.awt.Color(255, 255, 255));
        chRotatePanel.setMaximumSize(new java.awt.Dimension(300, 300));
        chRotatePanel.setMinimumSize(new java.awt.Dimension(300, 300));

        txtChRotate.setEditable(false);
        txtChRotate.setBackground(new java.awt.Color(102, 102, 102));
        txtChRotate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtChRotate.setForeground(new java.awt.Color(255, 255, 255));
        txtChRotate.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtChRotate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtChRotateKeyPressed(evt);
            }
        });

        btExitRotate.setBackground(new java.awt.Color(0, 0, 0));
        btExitRotate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btExitRotate.setForeground(new java.awt.Color(255, 255, 255));
        btExitRotate.setText("DONE");
        btExitRotate.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btExitRotate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btExitRotate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExitRotateActionPerformed(evt);
            }
        });

        lbChRotate.setForeground(new java.awt.Color(255, 255, 255));
        lbChRotate.setText("PRESS A KEY TO SELECT");

        javax.swing.GroupLayout chRotatePanelLayout = new javax.swing.GroupLayout(chRotatePanel);
        chRotatePanel.setLayout(chRotatePanelLayout);
        chRotatePanelLayout.setHorizontalGroup(
            chRotatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, chRotatePanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lbChRotate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtChRotate, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
            .addGroup(chRotatePanelLayout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(btExitRotate, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        chRotatePanelLayout.setVerticalGroup(
            chRotatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(chRotatePanelLayout.createSequentialGroup()
                .addContainerGap(91, Short.MAX_VALUE)
                .addGroup(chRotatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtChRotate, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                    .addComponent(lbChRotate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(58, 58, 58)
                .addComponent(btExitRotate)
                .addGap(83, 83, 83))
        );

        javax.swing.GroupLayout dialogChRotateLayout = new javax.swing.GroupLayout(dialogChRotate.getContentPane());
        dialogChRotate.getContentPane().setLayout(dialogChRotateLayout);
        dialogChRotateLayout.setHorizontalGroup(
            dialogChRotateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(dialogChRotateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(dialogChRotateLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(chRotatePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        dialogChRotateLayout.setVerticalGroup(
            dialogChRotateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(dialogChRotateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(dialogChRotateLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(chRotatePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        dialogChFall.setMinimumSize(new java.awt.Dimension(300, 300));
        dialogChFall.setResizable(false);

        chFallPanel.setBackground(new java.awt.Color(0, 0, 51));
        chFallPanel.setForeground(new java.awt.Color(255, 255, 255));
        chFallPanel.setMaximumSize(new java.awt.Dimension(300, 300));
        chFallPanel.setMinimumSize(new java.awt.Dimension(300, 300));

        txtChFall.setEditable(false);
        txtChFall.setBackground(new java.awt.Color(102, 102, 102));
        txtChFall.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtChFall.setForeground(new java.awt.Color(255, 255, 255));
        txtChFall.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtChFall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtChFallActionPerformed(evt);
            }
        });
        txtChFall.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtChFallKeyPressed(evt);
            }
        });

        btExitFall.setBackground(new java.awt.Color(0, 0, 0));
        btExitFall.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btExitFall.setForeground(new java.awt.Color(255, 255, 255));
        btExitFall.setText("DONE");
        btExitFall.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btExitFall.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btExitFall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExitFallActionPerformed(evt);
            }
        });

        lbChFall.setForeground(new java.awt.Color(255, 255, 255));
        lbChFall.setText("PRESS A KEY TO SELECT");

        javax.swing.GroupLayout chFallPanelLayout = new javax.swing.GroupLayout(chFallPanel);
        chFallPanel.setLayout(chFallPanelLayout);
        chFallPanelLayout.setHorizontalGroup(
            chFallPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, chFallPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lbChFall, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtChFall, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
            .addGroup(chFallPanelLayout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(btExitFall, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        chFallPanelLayout.setVerticalGroup(
            chFallPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(chFallPanelLayout.createSequentialGroup()
                .addContainerGap(91, Short.MAX_VALUE)
                .addGroup(chFallPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtChFall, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                    .addComponent(lbChFall, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(58, 58, 58)
                .addComponent(btExitFall)
                .addGap(83, 83, 83))
        );

        javax.swing.GroupLayout dialogChFallLayout = new javax.swing.GroupLayout(dialogChFall.getContentPane());
        dialogChFall.getContentPane().setLayout(dialogChFallLayout);
        dialogChFallLayout.setHorizontalGroup(
            dialogChFallLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(dialogChFallLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(dialogChFallLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(chFallPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        dialogChFallLayout.setVerticalGroup(
            dialogChFallLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(dialogChFallLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(dialogChFallLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(chFallPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        configName.setMaximumSize(new java.awt.Dimension(450, 300));
        configName.setMinimumSize(new java.awt.Dimension(450, 300));
        configName.setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 0, 51));
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 125));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Choose a name for your config:");
        jPanel1.add(jLabel2);

        txtNameCfg.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNameCfg.setText("Name of file");
        txtNameCfg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameCfgActionPerformed(evt);
            }
        });
        jPanel1.add(txtNameCfg);

        btNameCfgFinish.setText("DONE");
        btNameCfgFinish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNameCfgFinishActionPerformed(evt);
            }
        });
        jPanel1.add(btNameCfgFinish);

        javax.swing.GroupLayout configNameLayout = new javax.swing.GroupLayout(configName.getContentPane());
        configName.getContentPane().setLayout(configNameLayout);
        configNameLayout.setHorizontalGroup(
            configNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
        );
        configNameLayout.setVerticalGroup(
            configNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(550, 500));
        setResizable(false);

        mainPanel.setBackground(new java.awt.Color(0, 0, 51));
        mainPanel.setMaximumSize(new java.awt.Dimension(550, 500));
        mainPanel.setMinimumSize(new java.awt.Dimension(550, 500));
        mainPanel.setPreferredSize(new java.awt.Dimension(550, 500));

        lbDown.setBackground(new java.awt.Color(102, 102, 102));
        lbDown.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbDown.setForeground(new java.awt.Color(255, 255, 255));
        lbDown.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbDown.setText("Move Down:");
        lbDown.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lbLeft.setBackground(new java.awt.Color(102, 102, 102));
        lbLeft.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbLeft.setForeground(new java.awt.Color(255, 255, 255));
        lbLeft.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbLeft.setText("Move Left:");
        lbLeft.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lbRight.setBackground(new java.awt.Color(102, 102, 102));
        lbRight.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbRight.setForeground(new java.awt.Color(255, 255, 255));
        lbRight.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbRight.setText("Move Right:");
        lbRight.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lbRotate.setBackground(new java.awt.Color(102, 102, 102));
        lbRotate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbRotate.setForeground(new java.awt.Color(255, 255, 255));
        lbRotate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbRotate.setText("Rotate:");
        lbRotate.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lbFall.setBackground(new java.awt.Color(102, 102, 102));
        lbFall.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbFall.setForeground(new java.awt.Color(255, 255, 255));
        lbFall.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbFall.setText("Fall Down:");
        lbFall.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btChDown.setBackground(new java.awt.Color(0, 0, 0));
        btChDown.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btChDown.setForeground(new java.awt.Color(255, 255, 255));
        btChDown.setText("btChDown");
        btChDown.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 2));
        btChDown.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btChDown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btChDownActionPerformed(evt);
            }
        });

        btChLeft.setBackground(new java.awt.Color(0, 0, 0));
        btChLeft.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btChLeft.setForeground(new java.awt.Color(255, 255, 255));
        btChLeft.setText("btChLeft");
        btChLeft.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 2));
        btChLeft.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btChLeft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btChLeftActionPerformed(evt);
            }
        });

        btChFall.setBackground(new java.awt.Color(0, 0, 0));
        btChFall.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btChFall.setForeground(new java.awt.Color(255, 255, 255));
        btChFall.setText("btChFall");
        btChFall.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        btChFall.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btChFall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btChFallActionPerformed(evt);
            }
        });

        btChRight.setBackground(new java.awt.Color(0, 0, 0));
        btChRight.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btChRight.setForeground(new java.awt.Color(255, 255, 255));
        btChRight.setText("btChRight");
        btChRight.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 2));
        btChRight.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btChRight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btChRightActionPerformed(evt);
            }
        });

        btChRotate.setBackground(new java.awt.Color(0, 0, 0));
        btChRotate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btChRotate.setForeground(new java.awt.Color(255, 255, 255));
        btChRotate.setText("btChRotate");
        btChRotate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 2));
        btChRotate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btChRotate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btChRotateActionPerformed(evt);
            }
        });

        btResDft.setBackground(new java.awt.Color(0, 0, 0));
        btResDft.setForeground(new java.awt.Color(255, 255, 255));
        btResDft.setText("RESTORE DEFAULTS");
        btResDft.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 2));
        btResDft.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btResDft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btResDftActionPerformed(evt);
            }
        });

        btSave.setBackground(new java.awt.Color(0, 0, 0));
        btSave.setForeground(new java.awt.Color(255, 255, 255));
        btSave.setText("SAVE");
        btSave.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 4));
        btSave.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSaveActionPerformed(evt);
            }
        });

        btCancel.setBackground(new java.awt.Color(0, 0, 0));
        btCancel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btCancel.setForeground(new java.awt.Color(255, 255, 255));
        btCancel.setText("CANCEL");
        btCancel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 4));
        btCancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CONTROLS MENU");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btDone.setBackground(new java.awt.Color(0, 0, 0));
        btDone.setForeground(new java.awt.Color(255, 255, 255));
        btDone.setText("DONE");
        btDone.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 4));
        btDone.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btDone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDoneActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("The name of the config will be:");

        lbnameCfg.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbnameCfg.setForeground(new java.awt.Color(255, 255, 255));
        lbnameCfg.setText("\"config.cfg\"");

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbLeft, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbRight, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbDown, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbRotate, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbFall, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(btSave, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btDone, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(btCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbnameCfg, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65))
                    .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                            .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btChRotate, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btChDown, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btChRight, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btChLeft, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btChFall, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(111, 111, 111))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                            .addComponent(btResDft, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(207, 207, 207)))))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbLeft, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btChLeft, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbRight, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btChRight, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbDown, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btChDown, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbRotate, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btChRotate, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbFall, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btChFall, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btResDft, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lbnameCfg, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btSave, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btDone, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btChLeftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btChLeftActionPerformed
        dialogChLeft.setVisible(true);
        dialogChLeft.setLocationRelativeTo(null);
    }//GEN-LAST:event_btChLeftActionPerformed

    private void btSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSaveActionPerformed
        configName.setLocationRelativeTo(null);
        configName.setVisible(true);
    }//GEN-LAST:event_btSaveActionPerformed

    private void btCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_btCancelActionPerformed

    private void btResDftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btResDftActionPerformed
        //revert key to its default and change respective button name       
        //left
        keyLeft = VK_LEFT; 
        btChLeft.setText(KeyEvent.getKeyText(keyLeft));
        //right
        keyRight = VK_RIGHT; 
        btChRight.setText(KeyEvent.getKeyText(keyRight));
        //down
        keyDown = VK_DOWN;
        btChDown.setText(KeyEvent.getKeyText(keyDown));
        //rotate
        keyRotate = VK_SPACE;
        btChRotate.setText(KeyEvent.getKeyText(keyRotate));
        //fall
        keyFall = VK_ENTER; 
        btChFall.setText(KeyEvent.getKeyText(keyFall));                
    }//GEN-LAST:event_btResDftActionPerformed

    private void btExitLeftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExitLeftActionPerformed
        dialogChLeft.setVisible(false);
    }//GEN-LAST:event_btExitLeftActionPerformed

    private void txtChLeftKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtChLeftKeyPressed
        int keyCode = evt.getKeyCode();
        keyLeft = keyCode;
        String strKey = KeyEvent.getKeyText(keyCode);
        txtChLeft.setText(strKey);
        btChLeft.setText(strKey);
    }//GEN-LAST:event_txtChLeftKeyPressed

    private void txtChRightKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtChRightKeyPressed
        int keyCode = evt.getKeyCode();
        keyRight = keyCode;
        String strKey = KeyEvent.getKeyText(keyCode);
        txtChRight.setText(strKey);
        btChRight.setText(strKey);
    }//GEN-LAST:event_txtChRightKeyPressed

    private void btExitRightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExitRightActionPerformed
        dialogChRight.setVisible(false);
    }//GEN-LAST:event_btExitRightActionPerformed

    private void txtChDownKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtChDownKeyPressed
        int keyCode = evt.getKeyCode();
        keyDown = keyCode;
        String strKey = KeyEvent.getKeyText(keyCode);
        txtChDown.setText(strKey);
        btChDown.setText(strKey);
    }//GEN-LAST:event_txtChDownKeyPressed

    private void btExitDownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExitDownActionPerformed
        dialogChDown.setVisible(false);
    }//GEN-LAST:event_btExitDownActionPerformed

    private void txtChRotateKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtChRotateKeyPressed
        int keyCode = evt.getKeyCode();
        keyRotate = keyCode;
        String strKey = KeyEvent.getKeyText(keyCode);
        txtChRotate.setText(strKey);
        btChRotate.setText(strKey);
    }//GEN-LAST:event_txtChRotateKeyPressed

    private void btExitRotateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExitRotateActionPerformed
        dialogChRotate.setVisible(false);
    }//GEN-LAST:event_btExitRotateActionPerformed

    private void txtChFallKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtChFallKeyPressed
        int keyCode = evt.getKeyCode();
        keyFall = keyCode;
        String strKey = KeyEvent.getKeyText(keyCode);
        txtChFall.setText(strKey);
        btChFall.setText(strKey);
    }//GEN-LAST:event_txtChFallKeyPressed

    private void btExitFallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExitFallActionPerformed
        dialogChFall.setVisible(false);
    }//GEN-LAST:event_btExitFallActionPerformed

    private void txtChFallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtChFallActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtChFallActionPerformed

    private void btChDownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btChDownActionPerformed
        dialogChDown.setVisible(true);
        dialogChDown.setLocationRelativeTo(null);
    }//GEN-LAST:event_btChDownActionPerformed

    private void btChFallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btChFallActionPerformed
        dialogChFall.setVisible(true);
        dialogChFall.setLocationRelativeTo(null);
    }//GEN-LAST:event_btChFallActionPerformed

    private void btChRightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btChRightActionPerformed
        dialogChRight.setVisible(true);
        dialogChRight.setLocationRelativeTo(null);
    }//GEN-LAST:event_btChRightActionPerformed

    private void btChRotateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btChRotateActionPerformed
        dialogChRotate.setVisible(true);
        dialogChRotate.setLocationRelativeTo(null);
    }//GEN-LAST:event_btChRotateActionPerformed

    private void txtChRightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtChRightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtChRightActionPerformed

    private void txtNameCfgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameCfgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameCfgActionPerformed

    private void btNameCfgFinishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNameCfgFinishActionPerformed
        lbnameCfg.setText('"'+txtNameCfg.getText()+".cfg\"");
        configName.setVisible(false);
    }//GEN-LAST:event_btNameCfgFinishActionPerformed

    private void btDoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDoneActionPerformed
        //Delete current cfg before for creating a new one (naming issues)
        //Creates a new cfg with the selected keybinds
        config = new ConfigGame(keyLeft,keyRight,keyDown,keyRotate,keyFall);
        //saving the config
        try {            
            config.saveConfig(txtNameCfg.getText());
        } catch (Exception ex) {
            Logger.getLogger(ControlsMenu.class.getName()).log(Level.SEVERE, "COULDN´T SAVE CONFIG", ex);
        }
        //close the menu
        this.dispose();
    }//GEN-LAST:event_btDoneActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ControlsMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ControlsMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ControlsMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ControlsMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ControlsMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCancel;
    private javax.swing.JButton btChDown;
    private javax.swing.JButton btChFall;
    private javax.swing.JButton btChLeft;
    private javax.swing.JButton btChRight;
    private javax.swing.JButton btChRotate;
    private javax.swing.JButton btDone;
    private javax.swing.JButton btExitDown;
    private javax.swing.JButton btExitFall;
    private javax.swing.JButton btExitLeft;
    private javax.swing.JButton btExitRight;
    private javax.swing.JButton btExitRotate;
    private javax.swing.JButton btNameCfgFinish;
    private javax.swing.JButton btResDft;
    private javax.swing.JButton btSave;
    private javax.swing.JPanel chDownPanel;
    private javax.swing.JPanel chFallPanel;
    private javax.swing.JPanel chLeftPanel;
    private javax.swing.JPanel chRightPanel;
    private javax.swing.JPanel chRotatePanel;
    private javax.swing.JDialog configName;
    private javax.swing.JDialog dialogChDown;
    private javax.swing.JDialog dialogChFall;
    private javax.swing.JDialog dialogChLeft;
    private javax.swing.JDialog dialogChRight;
    private javax.swing.JDialog dialogChRotate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbChDown;
    private javax.swing.JLabel lbChFall;
    private javax.swing.JLabel lbChLeft;
    private javax.swing.JLabel lbChRight;
    private javax.swing.JLabel lbChRotate;
    private javax.swing.JLabel lbDown;
    private javax.swing.JLabel lbFall;
    private javax.swing.JLabel lbLeft;
    private javax.swing.JLabel lbRight;
    private javax.swing.JLabel lbRotate;
    private javax.swing.JLabel lbnameCfg;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTextField txtChDown;
    private javax.swing.JTextField txtChFall;
    private javax.swing.JTextField txtChLeft;
    private javax.swing.JTextField txtChRight;
    private javax.swing.JTextField txtChRotate;
    private javax.swing.JTextField txtNameCfg;
    // End of variables declaration//GEN-END:variables
}
