package supertetris.ui;

import java.awt.event.KeyEvent;
import supertetris.boards.ConfigGame;
import static java.awt.event.KeyEvent.*;

/**
 * this UI is used for the "information on how to play" menu in the tetris game
 * @author Andre Benquerer - n° 24633 
 */
public class HowToPlay extends javax.swing.JFrame {

    
    /**
     * Creates new form HowToPlay2
     */
    public HowToPlay() {
        initComponents();
        //sets the frame to the middle of the screen
        setLocationRelativeTo(null);
        try {//checks if a config exists and uses it to set the text for each key
            //loads the config         
            ConfigGame cfg = ConfigGame.loadConfig();
            //sets the text for each label based on the defined key in the cfg      
            mvLeft.setText(KeyEvent.getKeyText(cfg.getLeftkey())); 
            mvRight.setText(KeyEvent.getKeyText(cfg.getRigtkey())); 
            mvDown.setText(KeyEvent.getKeyText(cfg.getDownkey())); 
            mvRotate.setText(KeyEvent.getKeyText(cfg.getRotatekey())); 
            mvFall.setText(KeyEvent.getKeyText(cfg.getFalldownkey()));       
        } catch (Exception ex) {
            //if there is no cfg, than sets the label of each key to the default text.
            mvLeft.setText(KeyEvent.getKeyText(VK_LEFT)); 
            mvRight.setText(KeyEvent.getKeyText(VK_RIGHT)); 
            mvDown.setText(KeyEvent.getKeyText(VK_DOWN)); 
            mvRotate.setText(KeyEvent.getKeyText(VK_SPACE));  
            mvFall.setText(KeyEvent.getKeyText(VK_ENTER)); 
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        diaControls = new javax.swing.JDialog();
        jPanel9 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        mvLeft = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        mvRight = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        mvDown = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        mvRotate = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        mvFall = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        diaPlaying = new javax.swing.JDialog();
        jPanel20 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel21 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel29 = new javax.swing.JPanel();
        jPanel30 = new javax.swing.JPanel();
        diaScoring = new javax.swing.JDialog();
        jPanel31 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jPanel32 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jPanel40 = new javax.swing.JPanel();
        jPanel41 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btHtp = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btCtrls = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btScoring = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();

        diaControls.setMinimumSize(new java.awt.Dimension(500, 450));
        diaControls.setResizable(false);

        jPanel9.setBackground(new java.awt.Color(0, 0, 51));
        jPanel9.setLayout(new java.awt.BorderLayout());

        jLabel5.setBackground(new java.awt.Color(25, 26, 51));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("CONTROLS");
        jLabel5.setMaximumSize(new java.awt.Dimension(62, 50));
        jLabel5.setMinimumSize(new java.awt.Dimension(62, 50));
        jLabel5.setPreferredSize(new java.awt.Dimension(62, 50));
        jPanel9.add(jLabel5, java.awt.BorderLayout.NORTH);

        jPanel12.setBackground(new java.awt.Color(0, 0, 51));
        jPanel12.setLayout(new java.awt.GridLayout(0, 1, 0, 15));

        jPanel19.setBackground(new java.awt.Color(0, 0, 51));

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 45, Short.MAX_VALUE)
        );

        jPanel12.add(jPanel19);

        jPanel10.setBackground(new java.awt.Color(0, 0, 51));
        jPanel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jPanel10.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 75, 10));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Move Left");
        jLabel6.setPreferredSize(new java.awt.Dimension(80, 16));
        jPanel10.add(jLabel6);

        mvLeft.setForeground(new java.awt.Color(255, 255, 255));
        mvLeft.setText("jLabel7");
        jPanel10.add(mvLeft);

        jPanel12.add(jPanel10);

        jPanel11.setBackground(new java.awt.Color(0, 0, 51));
        jPanel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jPanel11.setForeground(new java.awt.Color(255, 255, 255));
        jPanel11.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 75, 10));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Move Right");
        jLabel8.setMaximumSize(new java.awt.Dimension(74, 30));
        jLabel8.setPreferredSize(new java.awt.Dimension(80, 16));
        jPanel11.add(jLabel8);

        mvRight.setForeground(new java.awt.Color(255, 255, 255));
        mvRight.setText("jLabel9");
        jPanel11.add(mvRight);

        jPanel12.add(jPanel11);

        jPanel15.setBackground(new java.awt.Color(0, 0, 51));
        jPanel15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jPanel15.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 75, 10));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Move Down");
        jLabel10.setPreferredSize(new java.awt.Dimension(80, 20));
        jPanel15.add(jLabel10);

        mvDown.setForeground(new java.awt.Color(255, 255, 255));
        mvDown.setText("jLabel11");
        jPanel15.add(mvDown);

        jPanel12.add(jPanel15);

        jPanel16.setBackground(new java.awt.Color(0, 0, 51));
        jPanel16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jPanel16.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 75, 10));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Rotate");
        jLabel12.setPreferredSize(new java.awt.Dimension(80, 16));
        jPanel16.add(jLabel12);

        mvRotate.setForeground(new java.awt.Color(255, 255, 255));
        mvRotate.setText("jLabel13");
        jPanel16.add(mvRotate);

        jPanel12.add(jPanel16);

        jPanel17.setBackground(new java.awt.Color(0, 0, 51));
        jPanel17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jPanel17.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 75, 10));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Fall down");
        jLabel14.setPreferredSize(new java.awt.Dimension(80, 16));
        jPanel17.add(jLabel14);

        mvFall.setForeground(new java.awt.Color(255, 255, 255));
        mvFall.setText("jLabel15");
        jPanel17.add(mvFall);

        jPanel12.add(jPanel17);

        jPanel18.setBackground(new java.awt.Color(0, 0, 51));

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 45, Short.MAX_VALUE)
        );

        jPanel12.add(jPanel18);

        jPanel9.add(jPanel12, java.awt.BorderLayout.CENTER);

        jPanel13.setBackground(new java.awt.Color(0, 0, 51));
        jPanel13.setPreferredSize(new java.awt.Dimension(50, 400));
        jPanel13.setRequestFocusEnabled(false);

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel9.add(jPanel13, java.awt.BorderLayout.WEST);

        jPanel14.setBackground(new java.awt.Color(0, 0, 51));
        jPanel14.setPreferredSize(new java.awt.Dimension(50, 400));

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 405, Short.MAX_VALUE)
        );

        jPanel9.add(jPanel14, java.awt.BorderLayout.EAST);

        javax.swing.GroupLayout diaControlsLayout = new javax.swing.GroupLayout(diaControls.getContentPane());
        diaControls.getContentPane().setLayout(diaControlsLayout);
        diaControlsLayout.setHorizontalGroup(
            diaControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        diaControlsLayout.setVerticalGroup(
            diaControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        diaPlaying.setMinimumSize(new java.awt.Dimension(500, 450));
        diaPlaying.setResizable(false);

        jPanel20.setBackground(new java.awt.Color(0, 0, 51));
        jPanel20.setLayout(new java.awt.BorderLayout());

        jLabel7.setBackground(new java.awt.Color(25, 26, 51));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("PLAYING THE GAME");
        jLabel7.setMaximumSize(new java.awt.Dimension(62, 50));
        jLabel7.setMinimumSize(new java.awt.Dimension(62, 50));
        jLabel7.setPreferredSize(new java.awt.Dimension(62, 50));
        jPanel20.add(jLabel7, java.awt.BorderLayout.NORTH);

        jPanel21.setBackground(new java.awt.Color(0, 0, 51));

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(0, 0, 51));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("Clear as many lines as possible by arranging the falling pieces to fill up the spaces on the board. Once a line is completely full, it will be cleared, and all the pieces above the line will fall down. Every time a piece can no longer fall down, a new piece will spawn. The game is over when there's no more space left for a piece to appear when generated. Place as many blocks as possible to allow more space to be cleared. You can use the controls to move the piece down, left, and right. The piece can also be rotated, and if you are sure where the piece will land, you can use the \"Fall Down\" key. (All the controls can be edited in the controls menu, which can also be accessed by pressing F1 on the main screen.)\n\nOn the board, you'll have controls to move the piece, and there's also a \"Recreate\" button. You can use it to create another board with your desired size and speed of falling.");
        jTextArea1.setWrapStyleWord(true);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel21Layout = new javax.swing.GroupLayout(jPanel21);
        jPanel21.setLayout(jPanel21Layout);
        jPanel21Layout.setHorizontalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel21Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel21Layout.setVerticalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel21Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel20.add(jPanel21, java.awt.BorderLayout.CENTER);

        jPanel29.setBackground(new java.awt.Color(0, 0, 51));
        jPanel29.setPreferredSize(new java.awt.Dimension(50, 400));
        jPanel29.setRequestFocusEnabled(false);

        javax.swing.GroupLayout jPanel29Layout = new javax.swing.GroupLayout(jPanel29);
        jPanel29.setLayout(jPanel29Layout);
        jPanel29Layout.setHorizontalGroup(
            jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel29Layout.setVerticalGroup(
            jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel20.add(jPanel29, java.awt.BorderLayout.WEST);

        jPanel30.setBackground(new java.awt.Color(0, 0, 51));
        jPanel30.setPreferredSize(new java.awt.Dimension(50, 400));

        javax.swing.GroupLayout jPanel30Layout = new javax.swing.GroupLayout(jPanel30);
        jPanel30.setLayout(jPanel30Layout);
        jPanel30Layout.setHorizontalGroup(
            jPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        jPanel30Layout.setVerticalGroup(
            jPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );

        jPanel20.add(jPanel30, java.awt.BorderLayout.EAST);

        javax.swing.GroupLayout diaPlayingLayout = new javax.swing.GroupLayout(diaPlaying.getContentPane());
        diaPlaying.getContentPane().setLayout(diaPlayingLayout);
        diaPlayingLayout.setHorizontalGroup(
            diaPlayingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        diaPlayingLayout.setVerticalGroup(
            diaPlayingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        diaScoring.setMinimumSize(new java.awt.Dimension(500, 450));
        diaScoring.setResizable(false);

        jPanel31.setBackground(new java.awt.Color(0, 0, 51));
        jPanel31.setLayout(new java.awt.BorderLayout());

        jLabel17.setBackground(new java.awt.Color(25, 26, 51));
        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("SCORING");
        jLabel17.setMaximumSize(new java.awt.Dimension(62, 50));
        jLabel17.setMinimumSize(new java.awt.Dimension(62, 50));
        jLabel17.setPreferredSize(new java.awt.Dimension(62, 50));
        jPanel31.add(jLabel17, java.awt.BorderLayout.NORTH);

        jPanel32.setBackground(new java.awt.Color(0, 0, 51));

        jTextArea2.setEditable(false);
        jTextArea2.setBackground(new java.awt.Color(0, 0, 51));
        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextArea2.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea2.setLineWrap(true);
        jTextArea2.setRows(5);
        jTextArea2.setText("During the game, you can earn points by:\n\nSuccessfully placing a piece in the board - 5 Points.\n\nMaking a piece Fall Down - 5 Points.\n\nCompleting a Line - 100 Points.\n\nThe selected speed at wich the board is created upon also applies a multiplier for the points:\n\nSpeed 0 - 0.8x\nSpeed 1 - Normal points.\nSpeed 2 - 1.2x\nSpeed 3 - 1.4x\nSpeed 4 - 1.8x\nSpeed 5 - 2.0x\nSpeed 6 - 2.5x\nSpeed 7 - 3.0x\nSpeed 8 - 5.0x\nSpeed 9 - 100x");
        jTextArea2.setWrapStyleWord(true);
        jScrollPane3.setViewportView(jTextArea2);

        javax.swing.GroupLayout jPanel32Layout = new javax.swing.GroupLayout(jPanel32);
        jPanel32.setLayout(jPanel32Layout);
        jPanel32Layout.setHorizontalGroup(
            jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel32Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 383, Short.MAX_VALUE)
                .addGap(9, 9, 9))
        );
        jPanel32Layout.setVerticalGroup(
            jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel32Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel31.add(jPanel32, java.awt.BorderLayout.CENTER);

        jPanel40.setBackground(new java.awt.Color(0, 0, 51));
        jPanel40.setPreferredSize(new java.awt.Dimension(50, 400));
        jPanel40.setRequestFocusEnabled(false);

        javax.swing.GroupLayout jPanel40Layout = new javax.swing.GroupLayout(jPanel40);
        jPanel40.setLayout(jPanel40Layout);
        jPanel40Layout.setHorizontalGroup(
            jPanel40Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel40Layout.setVerticalGroup(
            jPanel40Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel31.add(jPanel40, java.awt.BorderLayout.WEST);

        jPanel41.setBackground(new java.awt.Color(0, 0, 51));
        jPanel41.setPreferredSize(new java.awt.Dimension(50, 400));

        javax.swing.GroupLayout jPanel41Layout = new javax.swing.GroupLayout(jPanel41);
        jPanel41.setLayout(jPanel41Layout);
        jPanel41Layout.setHorizontalGroup(
            jPanel41Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        jPanel41Layout.setVerticalGroup(
            jPanel41Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );

        jPanel31.add(jPanel41, java.awt.BorderLayout.EAST);

        javax.swing.GroupLayout diaScoringLayout = new javax.swing.GroupLayout(diaScoring.getContentPane());
        diaScoring.getContentPane().setLayout(diaScoringLayout);
        diaScoringLayout.setHorizontalGroup(
            diaScoringLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        diaScoringLayout.setVerticalGroup(
            diaScoringLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(25, 26, 51));
        setMinimumSize(new java.awt.Dimension(800, 550));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 0, 51));
        jPanel1.setMaximumSize(new java.awt.Dimension(850, 550));
        jPanel1.setMinimumSize(new java.awt.Dimension(850, 550));
        jPanel1.setPreferredSize(new java.awt.Dimension(850, 550));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel1.setBackground(new java.awt.Color(25, 26, 51));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("HOW TO PLAY");
        jLabel1.setPreferredSize(new java.awt.Dimension(164, 100));
        jPanel1.add(jLabel1, java.awt.BorderLayout.NORTH);

        jPanel2.setBackground(new java.awt.Color(0, 0, 51));
        jPanel2.setLayout(new java.awt.GridLayout(0, 1, 50, 20));

        jPanel3.setBackground(new java.awt.Color(0, 0, 51));
        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 100, 25));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Playing Tetris");
        jLabel2.setMaximumSize(new java.awt.Dimension(200, 25));
        jLabel2.setMinimumSize(new java.awt.Dimension(200, 25));
        jLabel2.setPreferredSize(new java.awt.Dimension(200, 25));
        jPanel3.add(jLabel2);

        btHtp.setBackground(new java.awt.Color(0, 0, 0));
        btHtp.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btHtp.setForeground(new java.awt.Color(255, 255, 255));
        btHtp.setText("Show");
        btHtp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 3));
        btHtp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btHtp.setMaximumSize(new java.awt.Dimension(150, 50));
        btHtp.setMinimumSize(new java.awt.Dimension(150, 50));
        btHtp.setPreferredSize(new java.awt.Dimension(150, 50));
        btHtp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHtpActionPerformed(evt);
            }
        });
        jPanel3.add(btHtp);

        jPanel2.add(jPanel3);

        jPanel4.setBackground(new java.awt.Color(0, 0, 51));
        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 100, 25));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Controls");
        jLabel3.setMaximumSize(new java.awt.Dimension(200, 25));
        jLabel3.setMinimumSize(new java.awt.Dimension(200, 25));
        jLabel3.setPreferredSize(new java.awt.Dimension(200, 25));
        jPanel4.add(jLabel3);

        btCtrls.setBackground(new java.awt.Color(0, 0, 0));
        btCtrls.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btCtrls.setForeground(new java.awt.Color(255, 255, 255));
        btCtrls.setText("Show");
        btCtrls.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 3));
        btCtrls.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btCtrls.setMaximumSize(new java.awt.Dimension(150, 50));
        btCtrls.setMinimumSize(new java.awt.Dimension(150, 50));
        btCtrls.setPreferredSize(new java.awt.Dimension(150, 50));
        btCtrls.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCtrlsActionPerformed(evt);
            }
        });
        jPanel4.add(btCtrls);

        jPanel2.add(jPanel4);

        jPanel7.setBackground(new java.awt.Color(0, 0, 51));
        jPanel7.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 100, 25));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Scoring System");
        jLabel4.setMaximumSize(new java.awt.Dimension(200, 25));
        jLabel4.setMinimumSize(new java.awt.Dimension(200, 25));
        jLabel4.setPreferredSize(new java.awt.Dimension(200, 25));
        jPanel7.add(jLabel4);

        btScoring.setBackground(new java.awt.Color(0, 0, 0));
        btScoring.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btScoring.setForeground(new java.awt.Color(255, 255, 255));
        btScoring.setText("Show");
        btScoring.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 3));
        btScoring.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btScoring.setMaximumSize(new java.awt.Dimension(150, 50));
        btScoring.setMinimumSize(new java.awt.Dimension(150, 50));
        btScoring.setPreferredSize(new java.awt.Dimension(150, 50));
        btScoring.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btScoringActionPerformed(evt);
            }
        });
        jPanel7.add(btScoring);

        jPanel2.add(jPanel7);

        jPanel1.add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanel5.setBackground(new java.awt.Color(0, 0, 51));
        jPanel5.setPreferredSize(new java.awt.Dimension(150, 518));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel5, java.awt.BorderLayout.WEST);

        jPanel6.setBackground(new java.awt.Color(0, 0, 51));
        jPanel6.setPreferredSize(new java.awt.Dimension(150, 518));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel6, java.awt.BorderLayout.EAST);

        jPanel8.setBackground(new java.awt.Color(0, 0, 51));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 850, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel8, java.awt.BorderLayout.SOUTH);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 850, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btCtrlsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCtrlsActionPerformed
        //Makes the dialog visible
        diaControls.setVisible(true);
        //sets its position in the middle of the screen
        diaControls.setLocationRelativeTo(null);
    }//GEN-LAST:event_btCtrlsActionPerformed

    private void btScoringActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btScoringActionPerformed
        //Makes the dialog visible
        diaScoring.setVisible(true);
        //sets its position in the middle of the screen
        diaScoring.setLocationRelativeTo(null);
    }//GEN-LAST:event_btScoringActionPerformed

    private void btHtpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHtpActionPerformed
        //Makes the dialog visible
        diaPlaying.setVisible(true);
        //sets its position in the middle of the screen
        diaPlaying.setLocationRelativeTo(null);
    }//GEN-LAST:event_btHtpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HowToPlay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HowToPlay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HowToPlay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HowToPlay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HowToPlay().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCtrls;
    private javax.swing.JButton btHtp;
    private javax.swing.JButton btScoring;
    private javax.swing.JDialog diaControls;
    private javax.swing.JDialog diaPlaying;
    private javax.swing.JDialog diaScoring;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JPanel jPanel32;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel40;
    private javax.swing.JPanel jPanel41;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JLabel mvDown;
    private javax.swing.JLabel mvFall;
    private javax.swing.JLabel mvLeft;
    private javax.swing.JLabel mvRight;
    private javax.swing.JLabel mvRotate;
    // End of variables declaration//GEN-END:variables
}
