package supertetris.ui;

import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.sound.sampled.FloatControl;

/**
 * this UI is used for the main menu in the tetris game
 * @author Andre Benquerer - n° 24633
 */
public class StartScreen extends javax.swing.JFrame {
    String cfgName = "nada";
            
    public StartScreen() {
        initComponents();
        //sets the title of the main screen
        setTitle("Block Tetris");
        //sets the frame to the middle of the screen
        setLocationRelativeTo(null);
        //plays the main theme
        playTheme();
    }

    void playTheme() {
        try {//tries to set and play the music for the game
            //defines the file for the music
            AudioInputStream ais = AudioSystem.getAudioInputStream( getClass().getResourceAsStream("../resources/MainTheme.wav"));
            //creates a clip
            Clip mainTheme = AudioSystem.getClip();
            //enables the clip to be played
            mainTheme.open(ais);
            
            FloatControl volumeControl = (FloatControl) mainTheme.getControl(FloatControl.Type.MASTER_GAIN);
            float volume = -30.0f; // 0.0f (full volume) and -80.0f (mute)
            volumeControl.setValue(volume);
            
            //loops the music
            mainTheme.loop(Clip.LOOP_CONTINUOUSLY);
        }catch(Exception ex){
            System.out.println(ex);
        }
               
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cfgChooser = new javax.swing.JFileChooser();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btPlay = new javax.swing.JButton();
        btHtp = new javax.swing.JButton();
        btInfo = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lbSelectedConfig = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        btExit = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuGame = new javax.swing.JMenu();
        cfgControls = new javax.swing.JMenuItem();

        cfgChooser.setCurrentDirectory(new java.io.File("C:\\Users\\Andre\\Desktop\\POO\\BlockTetris"));
        cfgChooser.setDialogTitle("Chose desired cfg");
        cfgChooser.setMaximumSize(new java.awt.Dimension(597, 347));
        cfgChooser.setMinimumSize(new java.awt.Dimension(597, 347));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(25, 26, 51));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowDeactivated(java.awt.event.WindowEvent evt) {
                formWindowDeactivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 0, 51));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.GridLayout(0, 1, 20, 35));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/supertetris/resources/logo.png"))); // NOI18N
        jLabel1.setText("Block Tetris");
        jPanel1.add(jLabel1);

        btPlay.setBackground(new java.awt.Color(0, 0, 0));
        btPlay.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btPlay.setForeground(new java.awt.Color(255, 255, 255));
        btPlay.setText("Play now!");
        btPlay.setToolTipText("Start Playing");
        btPlay.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 4));
        btPlay.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPlayActionPerformed(evt);
            }
        });
        jPanel1.add(btPlay);

        btHtp.setBackground(new java.awt.Color(0, 0, 0));
        btHtp.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btHtp.setForeground(new java.awt.Color(255, 255, 255));
        btHtp.setText("How to Play");
        btHtp.setToolTipText("Click for playing informations");
        btHtp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 4));
        btHtp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btHtp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHtpActionPerformed(evt);
            }
        });
        jPanel1.add(btHtp);

        btInfo.setBackground(new java.awt.Color(0, 0, 0));
        btInfo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btInfo.setForeground(new java.awt.Color(255, 255, 255));
        btInfo.setText("Informations");
        btInfo.setToolTipText("Infos about the project and devs");
        btInfo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 4));
        btInfo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInfoActionPerformed(evt);
            }
        });
        jPanel1.add(btInfo);

        jPanel5.setBackground(new java.awt.Color(0, 0, 51));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Current config: ");

        lbSelectedConfig.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbSelectedConfig.setForeground(new java.awt.Color(255, 255, 255));
        lbSelectedConfig.setText("Config.cfg");

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("Change");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbSelectedConfig, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbSelectedConfig, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        jPanel1.add(jPanel5);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setBackground(new java.awt.Color(0, 0, 51));
        jPanel2.setMaximumSize(new java.awt.Dimension(50, 32767));
        jPanel2.setMinimumSize(new java.awt.Dimension(50, 0));
        jPanel2.setPreferredSize(new java.awt.Dimension(50, 478));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 424, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.WEST);

        jPanel3.setBackground(new java.awt.Color(0, 0, 51));
        jPanel3.setMaximumSize(new java.awt.Dimension(50, 32767));
        jPanel3.setMinimumSize(new java.awt.Dimension(50, 0));
        jPanel3.setPreferredSize(new java.awt.Dimension(50, 100));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 424, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3, java.awt.BorderLayout.EAST);

        jPanel4.setBackground(new java.awt.Color(0, 0, 51));
        jPanel4.setPreferredSize(new java.awt.Dimension(513, 10));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 436, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel4, java.awt.BorderLayout.PAGE_START);

        btExit.setBackground(new java.awt.Color(0, 0, 0));
        btExit.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btExit.setForeground(new java.awt.Color(255, 255, 255));
        btExit.setText("Exit Game");
        btExit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 4));
        btExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExitActionPerformed(evt);
            }
        });
        getContentPane().add(btExit, java.awt.BorderLayout.SOUTH);

        jMenu1.setText("Game");
        jMenuBar1.add(jMenu1);

        menuGame.setText("Menu");

        cfgControls.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        cfgControls.setText("Controls");
        cfgControls.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cfgControlsActionPerformed(evt);
            }
        });
        menuGame.add(cfgControls);

        jMenuBar1.add(menuGame);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cfgControlsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cfgControlsActionPerformed
        new ControlsMenu().show();
    }//GEN-LAST:event_cfgControlsActionPerformed

    private void btExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExitActionPerformed
        dispose();
    }//GEN-LAST:event_btExitActionPerformed

    private void btPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPlayActionPerformed
        cfgName = lbSelectedConfig.getText();
        if (cfgName == "nada"){
            new TetrisBoard().show();
        }else{
            new TetrisBoard(cfgName).show();
        }
    }//GEN-LAST:event_btPlayActionPerformed

    private void btHtpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHtpActionPerformed
        new HowToPlay().show();
    }//GEN-LAST:event_btHtpActionPerformed

    private void btInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInfoActionPerformed
        new AboutUs().show();
    }//GEN-LAST:event_btInfoActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        
    }//GEN-LAST:event_formWindowActivated

    private void formWindowDeactivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowDeactivated

    }//GEN-LAST:event_formWindowDeactivated

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       cfgChooser.showOpenDialog(this);
       String filename = cfgChooser.getSelectedFile().getName();
       cfgName = filename;
       lbSelectedConfig.setText(filename);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StartScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StartScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StartScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StartScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StartScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btExit;
    private javax.swing.JButton btHtp;
    private javax.swing.JButton btInfo;
    private javax.swing.JButton btPlay;
    private javax.swing.JFileChooser cfgChooser;
    private javax.swing.JMenuItem cfgControls;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lbSelectedConfig;
    private javax.swing.JMenu menuGame;
    // End of variables declaration//GEN-END:variables
}
